#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x58D0EE648A48B3BB (faure@kde.org)
#
Name     : kdesignerplugin
Version  : 5.100.0
Release  : 72
URL      : https://download.kde.org/stable/frameworks/5.100/portingAids/kdesignerplugin-5.100.0.tar.xz
Source0  : https://download.kde.org/stable/frameworks/5.100/portingAids/kdesignerplugin-5.100.0.tar.xz
Source1  : https://download.kde.org/stable/frameworks/5.100/portingAids/kdesignerplugin-5.100.0.tar.xz.sig
Summary  : Integration of Frameworks widgets in Qt Designer/Creator
Group    : Development/Tools
License  : LGPL-2.1
Requires: kdesignerplugin-bin = %{version}-%{release}
Requires: kdesignerplugin-license = %{version}-%{release}
Requires: kdesignerplugin-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules
BuildRequires : extra-cmake-modules-data
BuildRequires : kconfig-dev
BuildRequires : kcoreaddons-dev
BuildRequires : kdoctools-dev
BuildRequires : kplotting-dev
BuildRequires : qtbase-dev
BuildRequires : qttools-dev

%description
# KDesignerPlugin
Integrating custom widgets with Qt Designer
This tool is deprecated. In your CMake-based build system use [ECMAddQtDesignerPlugin](https://api.kde.org/ecm/module/ECMAddQtDesignerPlugin.html) from "Extra CMake Modules" instead.

%package bin
Summary: bin components for the kdesignerplugin package.
Group: Binaries
Requires: kdesignerplugin-license = %{version}-%{release}

%description bin
bin components for the kdesignerplugin package.


%package dev
Summary: dev components for the kdesignerplugin package.
Group: Development
Requires: kdesignerplugin-bin = %{version}-%{release}
Provides: kdesignerplugin-devel = %{version}-%{release}
Requires: kdesignerplugin = %{version}-%{release}

%description dev
dev components for the kdesignerplugin package.


%package license
Summary: license components for the kdesignerplugin package.
Group: Default

%description license
license components for the kdesignerplugin package.


%package man
Summary: man components for the kdesignerplugin package.
Group: Default

%description man
man components for the kdesignerplugin package.


%prep
%setup -q -n kdesignerplugin-5.100.0
cd %{_builddir}/kdesignerplugin-5.100.0

%build
## build_prepend content
# Make sure the package only builds if kdoctools has been updated first
sed -i -r -e 's,(KF.?DocTools \$\{KF.?_DEP_VERSION\})(.*\))$,\1 REQUIRED \2,' CMakeLists.txt
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1668451094
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1668451094
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kdesignerplugin
cp %{_builddir}/kdesignerplugin-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/kdesignerplugin/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/kgendesignerplugin

%files dev
%defattr(-,root,root,-)
/usr/lib64/cmake/KF5DesignerPlugin/KF5DesignerPluginConfig.cmake
/usr/lib64/cmake/KF5DesignerPlugin/KF5DesignerPluginConfigVersion.cmake
/usr/lib64/cmake/KF5DesignerPlugin/KF5DesignerPluginMacros.cmake
/usr/lib64/cmake/KF5DesignerPlugin/KF5DesignerPluginTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5DesignerPlugin/KF5DesignerPluginTargets.cmake

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kdesignerplugin/9a1929f4700d2407c70b507b3b2aaf6226a9543c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/ca/man1/kgendesignerplugin.1
/usr/share/man/ca@valencia/man1/kgendesignerplugin.1
/usr/share/man/de/man1/kgendesignerplugin.1
/usr/share/man/es/man1/kgendesignerplugin.1
/usr/share/man/it/man1/kgendesignerplugin.1
/usr/share/man/man1/kgendesignerplugin.1
/usr/share/man/nl/man1/kgendesignerplugin.1
/usr/share/man/pt/man1/kgendesignerplugin.1
/usr/share/man/pt_BR/man1/kgendesignerplugin.1
/usr/share/man/sv/man1/kgendesignerplugin.1
/usr/share/man/uk/man1/kgendesignerplugin.1
